using System;
using System.Collections.Generic;
using UnityEngine;

namespace VoidMart.Data
{
    /// <summary>
    /// Bitmap display font generated by the art pipeline.  Void Mart draws its own chunky
    /// geometric typeface instead of depending on an imported font, so the look is consistent on
    /// every platform and the weight/rounding can be re-tuned from the Master Tool.
    /// All metrics are in em units (1.0 == <see cref="pixelHeight"/>).
    /// </summary>
    [CreateAssetMenu(fileName = "VMFont", menuName = "VoidMart/Display Font", order = 2)]
    public class VMFontAsset : ScriptableObject
    {
        [Serializable]
        public struct Glyph
        {
            public int codePoint;
            public Rect uv;        // normalised atlas rect
            public Vector2 size;   // em
            public Vector2 bearing;// em, from pen position on the baseline
            public float advance;  // em
        }

        public Texture2D atlas;
        public Material material;
        public int pixelHeight = 72;
        public float lineHeight = 1.24f;
        public float ascender = 0.78f;
        public float descender = -0.22f;
        public float spaceAdvance = 0.32f;
        public Glyph[] glyphs = Array.Empty<Glyph>();

        Dictionary<int, int> m_Lookup;

        void OnEnable() => m_Lookup = null;

        public void InvalidateCache() => m_Lookup = null;

        public bool TryGetGlyph(char c, out Glyph glyph)
        {
            if (m_Lookup == null)
            {
                m_Lookup = new Dictionary<int, int>(glyphs.Length);
                for (int i = 0; i < glyphs.Length; i++) m_Lookup[glyphs[i].codePoint] = i;
            }
            if (m_Lookup.TryGetValue(c, out int index))
            {
                glyph = glyphs[index];
                return true;
            }
            glyph = default;
            return false;
        }

        /// <summary>Width of a string in em units at the given tracking.</summary>
        public float Measure(string text, float tracking)
        {
            if (string.IsNullOrEmpty(text)) return 0f;
            float width = 0f;
            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                if (c == ' ') { width += spaceAdvance + tracking; continue; }
                if (c == '\n') continue;
                width += (TryGetGlyph(c, out var g) ? g.advance : spaceAdvance) + tracking;
            }
            return Mathf.Max(0f, width - tracking);
        }
    }
}
