using UnityEngine;

namespace VoidMart.Core
{
    /// <summary>
    /// The single ScriptableObject that wires every channel together.  Generated by the
    /// one-click builder and handed to systems through <see cref="ServiceLocator"/>, so any
    /// subsystem can talk to any other without a scene reference.
    /// </summary>
    [CreateAssetMenu(fileName = "GameEventBus", menuName = "VoidMart/Event Bus")]
    public class GameEventBus : ScriptableObject
    {
        [Header("Economy")]
        public DoubleChannel cashChanged;
        public IntChannel gemsChanged;
        public FloatChannel xpChanged;
        public IntChannel playerLevelUp;
        public SaleChannel productSold;

        [Header("Hole / Gathering")]
        public SwallowChannel propSwallowed;
        public FloatChannel holeFillChanged;      // 0..1 capacity
        public IntChannel holeTierChanged;
        public SignalChannel holeFull;
        public FloatChannel unloadRate;           // mass / second into a hopper
        public SignalChannel unloadFinished;
        public SignalChannel feverStarted;
        public SignalChannel feverEnded;

        [Header("Store")]
        public StringChannel nodePurchased;
        public StringChannel machineJammed;
        public StringChannel machineRepaired;
        public IntChannel areaChanged;            // cast of WorldArea

        [Header("Puzzle")]
        public StringChannel puzzleRequested;     // payload = machine id
        public PuzzleChannel puzzleCompleted;

        [Header("Flow / UI")]
        public GameStateChannel stateChanged;
        public ToastChannel toast;
        public SignalChannel saveRequested;
        public SignalChannel dataReloaded;

        /// <summary>True when the generator has populated every channel reference.</summary>
        public bool IsComplete =>
            cashChanged && gemsChanged && xpChanged && playerLevelUp && productSold &&
            propSwallowed && holeFillChanged && holeTierChanged && holeFull && unloadRate &&
            unloadFinished && feverStarted && feverEnded && nodePurchased && machineJammed &&
            machineRepaired && areaChanged && puzzleRequested && puzzleCompleted &&
            stateChanged && toast && saveRequested && dataReloaded;
    }
}
